### ISSUE TITLE
GLPI 9.2.1

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/surveyticket#11]
Bonjour,
Est-il prévu d'avoir une version compatible glpi 9.2.x?
Merci

**Comment by ddurieux** [comment]
Oui, c'est en cours, il reste 1 ou 2 bugs à corriger avant de releaser

**Comment by eckorion** [comment]
Merci beaucoup
Bon courage ;)

**Comment by Vbouyenval** [comment]
Bonjour,

quand pensez vous que la release sera disponible ? 

Cordialement

**Comment by ddurieux** [comment]
Fin de semaine prochaine ;)

**Comment by Vbouyenval** [comment]
Super!

Merci Beaucoup 

Cordialement

**Comment by ddurieux** [comment]
Releasé
