### ISSUE TITLE
PB Questions

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/surveyticket#13]
Bonjour,
Je viens d'installer la version 9.2+1.0 sur GLPI 9.2.2
L'installation se passe bien, mais il m'est impossible de créer de nouvelles questions, j'ai une page vide 
![image](https://user-images.githubusercontent.com/25478777/38872618-fa1cbc70-4253-11e8-97dc-81663e59b9b6.png)
lorsque je clique sur "ajouter". Par contre la création de questionnaire fonctionne correctement à priori.
Cordialement

**Comment by ddurieux** [comment]
Je regarde ca d'ici quelques jours

**Comment by Vbouyenval** [comment]
Bonjour, je rencontre aussi le problème et j'ai constaté un autre problème. 

Pour tous les questionnaire avec des reponses prédefinis. Lors de la création du ticket , il n'affiche pas le champ libellé mais le champ numéro ID 

![image 18](https://user-images.githubusercontent.com/37873648/39044120-8b90ce48-448f-11e8-9445-60b7816cf6f3.jpg)

![image 19](https://user-images.githubusercontent.com/37873648/39044133-92c37d1e-448f-11e8-813e-99a955e22403.jpg)

**Comment by eckorion** [comment]
Oui j'ai le même problème également.

**Comment by Vbouyenval** [comment]
Bonjour,

Pensez vous résoudre ces problèmes prochainement ? 

Cordialement 
Mr BOUYENVAL Vincent

**Comment by ddurieux** [comment]
J'étais en vacances, là je ne sais pas encore quand je vais pouvoir m'en occuper

**Comment by Vbouyenval** [comment]
Bonjour,

Les problèmes sont toujours là 

![image](https://user-images.githubusercontent.com/37873648/40369589-9174fb00-5dde-11e8-9615-0aad96cefb98.png)

Cordialement

**Comment by ddurieux** [comment]
Ah ok, je crois que je n'ai pas regardé au bon endroit :(

je vais regarder

**Comment by Anass0505** [comment]
Salut j'ai un autre probleme j'ai installé la version 9.2+1.1 sur glpi 9.2.3 j'arrive a cree le formulaire a y repondre mais une fois le ticket créé la case description est vide il n'y est ecrit ni les reponses ni les quesition cela fait 1jour et demi que je cherche sans aucune evolution (je viens de commencer a faire du glpi mardi) Merci

**Comment by ddurieux** [comment]
autre problème, autre issue ;)
Merci !

**Comment by Vbouyenval** [comment]
Bonjour,

Désolé de revenir vers vous, avez vous une date pour la résolution du problème ? 

Math123789 as tu attaché ton questionnaire a un gabarit ? 

Merci de faire un nouveau post pour les problèmes différents de ce post.
Cordialement

**Comment by math123789** [comment]
oui j'ai belle et bien attaché mon questionnaire a un gabarie mais cela me renvoi vers un page blanche

**Comment by math123789** [comment]
mais je crois bien que je vais essayer de debuguer sa moi meme

**Comment by math123789** [comment]
C'est bon sa marche mais par contre j'ai toujour le meme probleme rencontré plus au les reponse au question s'affiche par ID et non par réponse en elle meme

**Comment by math123789** [comment]
Bonjour un autre bug a remarquer . Je ne peux que faire des questionnaire avec les incident et non le demande

**Comment by eckorion** [comment]
Bonjour, comme indiqué précédemment, merci de créer un autre ticket ou de vous rendre sur le forum.

**Comment by math123789** [comment]
Merci pour votre reponse mais je ne trouve pas le forum je croit qu'il n'ai indiquer null part

**Comment by math123789** [comment]
je suis vraiment desoler de vous redéranger  pour sa mais quelqu'un peux me donnez la solution pour avoir la reponse a la place de id quand une personne crée un ticket je suis vraiment en galérè et je dois lancer glpi le lundi qui arrive je suis en train de chercher dans le code pour voir d'ou vien l’erreur mais je galere

**Comment by Vbouyenval** [comment]
Bonjour,

Si vous lisez l'ensemble du forum , vous remarquerez que nous attendons tous la correction de ce problème ... 

Cordialement

**Comment by ddurieux** [comment]
je n'ai pas encore trouvé le temps de me pencher sur ce bug, j'espère dans les prochains jours

**Comment by eckorion** [comment]
Merci, bonne journée

**Comment by eckorion** [comment]
Bonjour,
Désolé de vous solliciter à nouveau, mais est-ce qu'éventuellement, si vous n'avez pas le temps vous pourriez nous donner quelques pistes pour qu'on essaye de regarder de notre côté?
Merci d'avance
