### ISSUE TITLE
Bug sur questionnaire

### ISSUE THREAD

**Issue by MicaENSL** [pluginsGLPI/surveyticket#2]
Bonjour,
depuis la mise à jour du plugin survey les questionnaires ne fonctionnent plus. Lorsqu'on crée un ticket dans une catégorie liée à un gabarit comprenant un questionnaire, le ticket ressemble à ceci une fois créé:
# 

Question : Bureau :
Texte : 89
# 

Question : Fournisseur 
Texte : 137

Les champs Texte ne contiennent pas le texte saisi mais des id.

Merci d'avance.

Mica

**Comment by tsmr** [comment]
Version de GLPI ?

**Comment by MicaENSL** [comment]
Testé sur 0.90.1 et 9.1

**Comment by amma35** [comment]
Les questions sont de quels types ? (Radio, Liste déroulante, .. )

**Comment by MicaENSL** [comment]
Après vérification le bug ne se produit qu'avec les questions du type Texte (court ou long).
Pas de problème avec les questions type liste déroulante ou oui/non

**Comment by MicaENSL** [comment]
Bonjour,
on a fini par trouver d'où ça venait. Pour info voici le diff:
```
--- ticket.class.php.orig       2016-11-02 15:14:13.237284958 +0100
+++ ticket.class.php    2016-11-02 15:30:46.200074050 +0100
@@ -621,7 +621,7 @@
                      $description .= "\n";
                      unset($ticket->input[$question]);
                   } else {
-                     $description .= __('Text', 'surveyticket') . " : " . str_replace('\r', "", $answer) . "\n";
+                     $description .= __('Text', 'surveyticket') . " : " . str_replace('\r', "", $realanswer) . "\n";
                      $description .= "\n";
                      unset($ticket->input[$question]);
                   }

```
A+

Mica

**Comment by amma35** [comment]
Merci, 
Je vais tester votre correction.

**Comment by amma35** [comment]
Bonjour,

Quelle version du plugin utilisez-vous ?

**Comment by MicaENSL** [comment]
0.90+1.0
