### ISSUE TITLE
Access permissions do not work

### ISSUE THREAD

**Issue by davidiasass** [pluginsGLPI/surveyticket#3]
I can not inhibit the edit option for the profile.

I wanted only the admin profile. Have permission to create and edit questions.

Profile option is not working.

In the attached image, even unchecked the option appears in the profile
![questoes](https://cloud.githubusercontent.com/assets/22041652/22330967/0063825c-e3b0-11e6-8781-13feb0bf9d1a.PNG)
![questoes01](https://cloud.githubusercontent.com/assets/22041652/22330996/25479536-e3b0-11e6-982e-8e1c02584c3d.PNG)

**Comment by amma35** [comment]
Can you test with the master if this is corrected?

**Comment by davidiasass** [comment]
It worked.

Congratulations thank you

**Comment by davidiasass** [comment]
It worked.

Congratulations thank you

**Comment by davidiasass** [comment]
I installed the master and now there is no option to bind to the calling template
![questoes3](https://cloud.githubusercontent.com/assets/22041652/22335287/405fcea0-e3c5-11e6-9a51-8047a0c5bf5e.PNG)

**Comment by amma35** [comment]
The last correction I made does not correct your problem?

**Comment by davidiasass** [comment]
Corrected the problem of inhibition. The link template option no longer appears.

**Comment by amma35** [comment]
It takes the right "CREATE" to add templates : 

![image](https://cloud.githubusercontent.com/assets/15138371/22373689/3d4934d4-e4a3-11e6-9cbc-8cc052b82d34.png)

**Comment by davidiasass** [comment]
This option does not appear.

I'm doing a direct insert directly into the table glpi_plugin_surveyticket_tickettemplates
![questoes4](https://cloud.githubusercontent.com/assets/22041652/22379339/1ce51c88-e4a0-11e6-9dc4-59cd230102c5.PNG)

**Comment by amma35** [comment]
Do you have this fix to bring in your ticket.class.php file? 
https://github.com/pluginsGLPI/surveyticket/commit/748a2bf5f874a3177f937afe3ea16c9056fda4be

**Comment by davidiasass** [comment]
I made the change and it worked. Thank you
