### ISSUE TITLE
Listing by Answer Name

### ISSUE THREAD

**Issue by jorgecamargosdb** [pluginsGLPI/surveyticket#7]
Hello,

I currently have Survey v0.90-1.0 installed in glpi v9.1.1, and the Answers listing is sorted by Answer ID. I would like to change the listing by the name of the Answer. How do I do?

Best Regards

**Comment by amma35** [comment]
The release is not output but there is a development that allows to sort the answers according to a classification. (https://forge.glpi-project.org/issues/5497)

![image](https://cloud.githubusercontent.com/assets/15138371/23067490/e5cc2e72-f51f-11e6-9390-ffc672242bc1.png)

You can use the master version to perform your tests.

**Comment by jorgecamargosdb** [comment]
Good Morning

I already tested the master version and changed line 512 of answer.class.php and it worked. However in version 0.90-1.0 I did not find where is the Answers listing

**Comment by amma35** [comment]
This feature didn't exist for version 0.90-1.0

**Comment by jorgecamargosdb** [comment]
OK. Tanks for your atention
