### ISSUE TITLE
Bug : lors de la création d'un ticket 

### ISSUE THREAD

**Issue by Pilloka** [pluginsGLPI/surveyticket#9]
Bonjour, 
j'ai un souci lorsque le plugin surveyticket est activé. Quand on crée un ticket sans questionnaire, un carré apparait alors qu'il devrait être caché, ce cadre contient le code  HTML de la description.

pour fair apparaitre le bug :
Je fais créer un ticket > je mets une description et un titre > j'ajoute un demandeur > et là le cadre apparait.

=================================================================

Hello,
i have a problem when surveyticket plugin is activated. When we create a ticket without survey, a big frame appears reflecting like mirror the description content in HTML. 

to make the bug happen : 
i create a ticket > i fill the description and title > the i add a client > And the frame appears.

[ glpi version 0.90.3, php 5.6, apache 2.4.10 et mariaDB 10.0.23 | Version du plugin 0.90+1.0 ]

**Comment by ddurieux** [comment]
I had tested with version 9.2+1.0 et pas de problème, ça a dû être corrigé entre-temps
